### ISSUE TITLE
Add instructions on how to donate

### ISSUE THREAD

**Issue by kevinburke** [gobridge/golangbridge.org#11]
I'd like to give money to Go Bridge to help support its mission, but it's not clear how to do this by reading the website, as I'm not a large company.

It would be nice if there was a PayPal link or similar, or at least text about "we are not accepting donations at this time."

**Comment by ardan-bkennedy** [comment]
Thanks again for reaching out. Here is a link to donate. Just mention it is for GoBridge. https://bridgefoundry.org/donate

I will get this on the website as soon as possible.
