### ISSUE TITLE
Add a chapters page

### ISSUE THREAD

**Issue by carlisia** [gobridge/golangbridge.org#7]
A sample page is below. @cassandraoid should give input.
# Main listing

Example:
https://www.girldevelopit.com/chapters

It might have a simpler/flatter organization since we don't have so many chapters
# Individual chapters

https://www.girldevelopit.com/chapters/san-diego
https://www.girldevelopit.com/chapters/los-angeles
# Chapters to add
- San Diego: Carlisia
- San Francisco: Cassandra
- Berlin: Natalie Pistunovich
- Remote Meetup: Gunjan

**Comment by freeformz** [comment]
See also: https://github.com/railsbridge/bridge_troll/issues/489
